# Generated by Django 5.0.6 on 2025-06-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipo",
            name="cmp",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ipo",
            name="current_return",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ipo",
            name="drhp_pdf_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="ipo",
            name="ipo_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="ipo",
            name="issue_size",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ipo",
            name="issue_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ipo",
            name="listing_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ipo",
            name="listing_gain",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ipo",
            name="listing_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="ipo",
            name="price_band",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ipo",
            name="rhp_pdf_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="ipo",
            name="close_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ipo",
            name="company_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="ipo",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="ipo_logos/"),
        ),
        migrations.AlterField(
            model_name="ipo",
            name="open_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ipo",
            name="status",
            field=models.CharField(
                choices=[
                    ("Upcoming", "Upcoming"),
                    ("Ongoing", "Ongoing"),
                    ("Listed", "Listed"),
                ],
                max_length=100,
            ),
        ),
    ]
