# Generated by Django 5.0.6 on 2025-06-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_ipo_cmp_ipo_current_return_ipo_drhp_pdf_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ipo",
            name="drhp_pdf_link",
        ),
        migrations.RemoveField(
            model_name="ipo",
            name="rhp_pdf_link",
        ),
        migrations.AddField(
            model_name="ipo",
            name="drhp_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ipo",
            name="final_listing_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ipo",
            name="rhp_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ipo",
            name="cmp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ipo",
            name="issue_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("book_building", "Book Building"),
                    ("fixed_price", "Fixed Price"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ipo",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
        migrations.AlterField(
            model_name="ipo",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("upcoming", "Upcoming"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
