# Generated by Django 5.0.6 on 2025-07-05 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipo_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ipo",
            name="current_market_price",
        ),
        migrations.RemoveField(
            model_name="ipo",
            name="drhp_pdf",
        ),
        migrations.RemoveField(
            model_name="ipo",
            name="ipo_price",
        ),
        migrations.RemoveField(
            model_name="ipo",
            name="listing_price",
        ),
        migrations.RemoveField(
            model_name="ipo",
            name="rhp_pdf",
        ),
        migrations.AddField(
            model_name="ipo",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ipo",
            name="company_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="ipo",
            name="issue_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="ipo",
            name="listing_date",
            field=models.DateField(default="2025-01-01"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ipo",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
        migrations.AlterField(
            model_name="ipo",
            name="price_band",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="ipo",
            name="status",
            field=models.CharField(max_length=50),
        ),
    ]
